### ISSUE TITLE
Y U NO TESTS

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/Omega#1]

**Comment by rob0rt** [comment]
I'LL TEST WHEN I'M DEAD

**Comment by rob0rt** [comment]
Or at least at a point where testing makes sense. Most things are still being changed a lot.

**Comment by dwetterau** [comment]
On this note, if you do end up doing some bitmask thing and as your models get more complicated, it would be great to write some tests for them.

**Comment by rob0rt** [comment]
Believe it or not I do actually intend to write tests for my helper classes at some point soon. Like User and Application and what not.

Probably going to use Travis since they have nice database setups.
