### ISSUE TITLE
Rename from Omega?

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#19]
Omega is fine for a temp name. But it should have a name that either better describes the service or is shorter for convenience.

Plus people don't like Omega.

**Comment by aaaanderson** [comment]
take a trip back to 2005 and use my.texaslan

**Comment by dwetterau** [comment]
Probs too late at this point because SSL cert

**Comment by aaaanderson** [comment]
we're stuck with a dumb goofy name and i'm very sad

**Comment by rob0rt** [comment]
I can still change it, all I have to do is invalidate the cert. It's not impossible.

I thought about my.texaslan but got a stronger negative option on that.

**Comment by aaaanderson** [comment]
xorbuttsbuttsbutts.texaslan

something

anything

**Comment by rob0rt** [comment]
WLAN was a name I came up with. It could potentially be hosted like w.lambdaalphanu.org

**Comment by gregorycerna** [comment]
Just call it lambda

**Comment by rob0rt** [comment]
I already ruled out Lambda

**Comment by arrdem** [comment]
who cares. omega works fine.

**Comment by rob0rt** [comment]
It looks like we're going to stick with Omega for the time being.

I'll leave this issue open for discussion in case any great suggestions come along.

**Comment by aaaanderson** [comment]
robertsucks.texaslan.org

any objections

**Comment by rob0rt** [comment]
One I can think of

**Comment by aaaanderson** [comment]
don't worry about the ssl cert they're p cheap

**Comment by rob0rt** [comment]
Oddly wasn't exactly what I was talking about

**Comment by arrdem** [comment]
It may be bad but now it's a tradition.
