### ISSUE TITLE
Y U NO CI

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/Omega#2]

**Comment by rob0rt** [comment]
I CODE IN PROD

**Comment by rob0rt** [comment]
Seriously though I **do** code in prod and should probably use some sort of CI.

**Comment by aaaanderson** [comment]
dumbass

**Comment by aaaanderson** [comment]
<3 <3 <3

**Comment by arrdem** [comment]
TBQH building CI for a website is really really hard especially when it's in active dev. I only ever test clojure-grimoire/grimoire's API and that's done via the clojure-grimoire/lib-grimoire API client's test suite.

**Comment by rob0rt** [comment]
Well eventually I'm going to pop up the official LAN server and we can host two versions of Omega on there, test and prod. Doesn't necessarily have to be different databases (go the ol' Facebook style of "development code running with production data"). From there CI would be fairly trivial.

But I still need tests.

So.

**Comment by aaaanderson** [comment]
pledge task: robert's qa intern

**Comment by rob0rt** [comment]
:+1:

**Comment by arrdem** [comment]
:+1:
