### ISSUE TITLE
Allow for password reset

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#27]
Reference: https://github.com/panique/huge/blob/master/application/model/PasswordResetModel.php

**Comment by rob0rt** [comment]
Started here: 595371e2d0365f

**Comment by arrdem** [comment]
pls 2 allow ssh key login <3

**Comment by rob0rt** [comment]
uh.

ppppppppppprrrrrrrrrrrrrrrrrooooooooooooooooobbbbbbbbbaaaaaaaaaaaaabbbbbbbbbbblllllllllllllyyyyyyyyyyyy not

**Comment by rob0rt** [comment]
1. Create password reset field in DB and update model
2. Uncomment https://github.com/TexasLAN/Omega/blob/master/lib/Auth.php#L128
3. Implement password reset controller on `/password` which accepts a query param `token`
4. `token` is used to look up the user and set a new password hash on the user using:
   https://github.com/TexasLAN/Omega/blob/master/models/UserMutator.php#L110-L112

**Comment by arrdem** [comment]
AYYYYYYYYY

**Comment by spxrogers** [comment]
BEEEEEEEEE

@arrdem
