### ISSUE TITLE
Get an SSL certificate 

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#29]
Nobody seems to have noticed I'm running this under HTTP and not HTTPS.

That should... Uh... Be fixed soon.

**Comment by dwetterau** [comment]
Free for the main domain and one subdomain: http://www.startssl.com/

**Comment by aaaanderson** [comment]
bobby pls be a security man and not a vulnerability man

**Comment by arrdem** [comment]
Good thing I used a password that totally isn't reused anywhere else ever

**Comment by aaaanderson** [comment]
patented bobby hash function

pw ^ "buttsbuttsbutts"

**Comment by rob0rt** [comment]
Yeah what if I hash with ^ "buttsbuttsbutts' sue me

**Comment by rob0rt** [comment]
BOOM SSL
