### ISSUE TITLE
CODE IS IN PHP Y U NO IO MONAD

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/Omega#3]

**Comment by rob0rt** [comment]
I'm not gonna lie this took longer than I thought it would

**Comment by dwetterau** [comment]
I have seen the light. And it is beautiful. 

https://github.com/ubolonton/js-csp

**Comment by rob0rt** [comment]
Do we _really_ want to go the route of server side JS.
**_really**_

**Comment by dwetterau** [comment]
...yes?

Or you know... Coffeescript?

**Comment by rob0rt** [comment]
The last application system was built in Node and with the number of dependent nested objects in the database it because callback hell very quickly.
I just went with a language that had the option to make IO synchronous and interacts with SQL databases easily.
