### ISSUE TITLE
Apply a License

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#36]
I'm thinking [MIT](http://choosealicense.com/licenses/mit/) but am totally up to suggestions

**Comment by rob0rt** [comment]
GNU GPL is my other choice

**Comment by arrdem** [comment]
BSD three clause or MIT. GPL can suck eggs.

**Comment by arrdem** [comment]
EPL would also be acceptable. Hell this doesn't even have to be free software. We (you) can claim full copyright over it and just happen to maintain it in a public manner.

**Comment by rob0rt** [comment]
Honestly though I'm perfectly cool with it being FOSS. I just want to throw some good license on it to explicitly state it being so.

**Comment by rob0rt** [comment]
What's the difference between [BSD 2-clause](http://choosealicense.com/licenses/bsd-2-clause/) and [BSD 3-clause](http://choosealicense.com/licenses/bsd-3-clause/)? Is 3-clause just more suited for an organization maintaining the software?

**Comment by arrdem** [comment]
urgh time to read licenses again

**Comment by rob0rt** [comment]
Is anyone **not** alright with [EPL](http://choosealicense.com/licenses/epl-1.0/) or [BSD 3-clause](http://choosealicense.com/licenses/bsd-3-clause/)? I'll be picking between those two.

**Comment by arrdem** [comment]
I would argue for EPL over BSD-3 because if someone fixes a bug let alone a real security flaw in whatever Omega becomes we want that. However either would do.

**Comment by rob0rt** [comment]
Sounds like a valid enough argument to me. EPL it is.

**Comment by arrdem** [comment]
:+1: :shipit:

**Comment by rob0rt** [comment]
Correct me if I'm wrong but I don't need file header comments for this license, right?

**Comment by arrdem** [comment]
You don't and I hate file header warnings.

**Comment by rob0rt** [comment]
I'm probably going to add file headers soon regardless.

Omega needs more comments.
