### ISSUE TITLE
Spice up the UI

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#37]
This is vanilla bootstrap with a pretty generic low-poly background. Some bootstrap theme or something of the sort would be a great enhancement just to the day-to-day usability of the service.

[Material Bootstrap](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) comes to mind but I'm open to other suggestions.

This is a very down-the-road change as well. System functionality comes before UI. That's why it was built with Bootstrap in the first place.

**Comment by dwetterau** [comment]
I've been using the material bootstrap stuff (beta.dwett.com / life.dwett.com) and I don't really recommend it. I've slowly been transitioning my stuff off of it to use material-ui components instead.

The main issue is that most of the effects are hacks, and some of the concepts of material design don't really line up with bootstrap (i.e. in that library, a "well" is actually the material Paper element). It also really doesn't play nicely with ANY jquery library I've tried to use with it (editors, tokenfields, date/time pickers) so tread carefully.

I think just a clean (less default) theme would be better (http://bootswatch.com/cosmo/ or /Spacelab or if you want something more true to material: /Paper on the same site.

**Comment by rob0rt** [comment]
Oh these are nice. I'll look into one of these!
