### ISSUE TITLE
store pictures

### ISSUE THREAD

**Issue by aaaanderson** [TexasLAN/Omega#50]
fuck paying for google drive space

**Comment by rob0rt** [comment]
lmfao I'm not doing blob storage.

Plus it would still need disk space to store stuff.

**Comment by aaaanderson** [comment]
couldn't you store on a cheaper place (like s3) then have an upload and
download portal here

this is all very laborious

**Comment by rob0rt** [comment]
We discussed linking Alpha to Omega. Having login with Omega or something via OAuth.

All very up in the air right now though.

**Comment by rob0rt** [comment]
Closing since this is the job of Alpha
