### ISSUE TITLE
Migrate to password_hash

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#58]
https://github.com/TexasLAN/Omega/blob/master/lib/dao/User.php#L36-L39

**Comment by spxrogers** [comment]
T.T

**Comment by aaaanderson** [comment]
:hankey:

**Comment by arrdem** [comment]
p l s 2 splain prblm n pr

**Comment by aaaanderson** [comment]
rite now we use :hankey: hash

we want 2 use :100: hash

need 2 reset passwords tho

**Comment by arrdem** [comment]
hum so after a little bit of googling it isn't obvious that there _is_ a better solution in PHP land. Wat do.

**Comment by rob0rt** [comment]
As I recall, this wasn't _bad_, someone from the HHVM team just told me there was something _better_.

**Comment by arrdem** [comment]
According to the official docs, `password_hash` is deprectated in favor of `crypt`, and is only a thin layer around it anyway. I don't see anything else remotely sane in the standard library. 

http://php.net/manual/en/function.crypt.php#example-5376 pertains. I think that we have to figure out what the strongest installed password hashing function is and then switch to that if we even care enough. I claim we don't.

**Comment by rob0rt** [comment]
I agree with that claim

**Comment by arrdem** [comment]
Closed because the maintainers are lazy bastards.
