### ISSUE TITLE
Refactor User roles

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/Omega#7]
It would probably be better if user roles were a single column in the database and access via a bitmask. For example:

``` php
$role1 = 1;
$role2 = 2;
$role3 = 4;

$user_role = 5;

if($user_role & $role1) {
  print "Role 1";
}
if($user_role & $role2) {
  print "Role 2";
}
if($user_role & $role_3) {
  print "Role 3;
}
```

Would produce the output

```
Role 1
Role 3
```

**Comment by dwetterau** [comment]
Ooooo no gross. Nothing screams unnecessary optimizations quite like a bitmask.

This is a relational database right? I think the better approach would be to keep adding boolean columns to it for each role. Then requesting users based off complex role queries (i.e. users in role1, role2, not in role3 or something) doesn't require any bitwise logic on the client side and stays behind a sql query. 

Another horrible issue with this would be if you ever wanted to query based off of a single role. With a bitmask approach you would have to retrieve them all and check them on the client side instead of a simple where role1=true.

**Comment by rob0rt** [comment]
That's actually an incredibly good point I didn't think of. The way it's implemented in the schema right now is every role is just a new column on the user table that contains a boolean true or false. I was just trying to figure out a way to make that better since it seems cumbersome to add a new role to the system. You do make a good point though. Would you suggest just going with that technique or do you have any other potential ways to deal with roles?

**Comment by rob0rt** [comment]
You can kind of see here how the different roles come into the User object as different columns in the database.

https://github.com/TexasLAN/Omega/blob/master/lib/User.php#L120-L122

**Comment by dwetterau** [comment]
So ideally what you would do (if you are using an ORM this should be easy) is make a table that belongs to the User table. Basically you have a roles table that you join with Users whenever you want to return a User + their roles. This means that adding a new role type / adding roles to a user is just an insert in this secondary table. The schema for the second table would just be "id[autoincrement] | UserId[int?] | RoleType[int]" which you join with the User table using the UserId column. 

This also means finding all roles for a user would be like "select \* from Roles where UserId=id" or whatever, pretty straightforward.

**Comment by rob0rt** [comment]
Ah I see what you're saying. Basically create a many to many relationship between Roles and Users.

I'll look into implementing that in the near future. Probably after I fix the type checker.

**Comment by dwetterau** [comment]
Yeah I was describing just a OneToMany but either would work if done right.

**Comment by rob0rt** [comment]
On a related note, it would be nice to be able to fix [this](https://github.com/TexasLAN/Omega/blob/master/lib/User.php#L112-L124) method so it's less manual to update, potentially using something like this:

``` php
private static function createFromQuery(array $query): User {
  $user = new User();
  foreach($query as $key => $value){
    $user->{$key} = $value;
  }
}
```

I'll probably have to do something to deal with types as well. Maybe `gettype`. That's probably also bad though. The User object's fields do map 1-to-1 with the database at this point, so maybe not.

**Comment by rob0rt** [comment]
Woo! Moved roles to their own table and gave them their own DAO.
