### ISSUE TITLE
Delete app doesn't do what it says

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/Omega#83]
`Review -> [app] -> Delete application` doesn't actually delete the app for some reason.

**Comment by rob0rt** [comment]
_once you're here, you're here forever_

**Comment by arrdem** [comment]
This is actually a problem tho since we have spam/troll apps this semester.

**Comment by rob0rt** [comment]
[this](https://github.com/TexasLAN/Omega/blob/master/controllers/review/ReviewSingleController.php#L47-L49) logic doesn't match up with [this logic](https://github.com/TexasLAN/Omega/blob/master/controllers/members/MembersController.php#L376-L379).

Just some missing post data that would get it into this case.

**Comment by arrdem** [comment]
Bump.

**Comment by rainiera** [comment]
+1
