### ISSUE TITLE
[New Feature] Comments to talk about from Actives in Officer Meeting Events

### ISSUE THREAD

**Issue by DrewRomanyk** [TexasLAN/Omega#85]
thx steven <3

**Comment by spxrogers** [comment]
@DrewRomanyk i'm just going to roll with adding a nav-button item labeled "Add Officer Item" that takes a simple post request. 

thoughts: 
- "post anonymously" option.
- publicly viewable submissions; aka an active going to post their thought can view previously submitted items for the week from other members on the page.
- admin/officer use: after talking about each item at the officer meeting marks an item as "closed" and is subsequently archived. archived items are hidden by default ofc. manually "closing" an item makes it easy to have an item-topic roll over a week if needed.
